default:
  tags: [linux]

variables:
  GIT_STRATEGY: clone
  GIT_DEPTH: "0"

stages:
  - build
  - publish

before_script:
  - export VERSION=`git2version -s`

build:
  stage: build
  script:
    - ./build.sh

publish:
  stage: publish
  when: manual
  script:
    - ./build.sh
    - ./publish.sh
