// AUTO-GENERATED FILE PLEASE DO NOT MODIFY MANUALLY
/* eslint-disable */
// @ts-nocheck

import { Library, std_n } from '@greycat/sdk';
import { core, runtime, io, debug, math, util, } from './lib/index.js';
export * from './lib/index.js';

export const stdlib: Library = {
  name: 'std',
  mapped: [],
  configure(loaders, factories) {
    loaders.set('core::String', (r) => {
      let len = r.read_varint32();
      if (len & 1) {
        len >>= 1;
        return r.abi.symbols[len];
      }
      len >>= 1;
      return r.read_string(len);
    });
    factories.set(core.GeoBox._type, core.GeoBox);
    factories.set(core.nodeList._type, core.nodeList);
    loaders.set(core.nodeList._type, std_n.core.nodeList.load);
    factories.set(core.TimeZone._type, core.TimeZone);
    factories.set(core.nodeIndexBucket._type, core.nodeIndexBucket);
    loaders.set(core.nodeIndexBucket._type, std_n.core.nodeIndexBucket.load);
    factories.set(core.node._type, core.node);
    loaders.set(core.node._type, std_n.core.node.load);
    factories.set(core.nodeTimeCursor._type, core.nodeTimeCursor);
    loaders.set(core.nodeTimeCursor._type, std_n.core.nodeTimeCursor.load);
    factories.set(core.TableColumnMeta._type, core.TableColumnMeta);
    factories.set(core.ti2d._type, core.ti2d);
    factories.set(core.Error._type, core.Error);
    loaders.set(core.Error._type, std_n.core.Error.load);
    factories.set(core.tf2d._type, core.tf2d);
    factories.set(core.ErrorCode._type, core.ErrorCode);
    factories.set(core.ti4d._type, core.ti4d);
    factories.set(core.SamplingMode._type, core.SamplingMode);
    factories.set(core.DurationUnit._type, core.DurationUnit);
    factories.set(core.TensorType._type, core.TensorType);
    factories.set(core.Table._type, core.Table);
    loaders.set(core.Table._type, std_n.core.Table.load);
    factories.set(core.geo._type, core.geo);
    loaders.set(core.geo._type, std_n.core.geo.load);
    factories.set(core.ti6d._type, core.ti6d);
    factories.set(core.Tensor._type, core.Tensor);
    loaders.set(core.Tensor._type, std_n.core.Tensor.load);
    factories.set(core.GeoCircle._type, core.GeoCircle);
    factories.set(core.Date._type, core.Date);
    loaders.set(core.Date._type, std_n.core.Date.load);
    factories.set(core.duration._type, core.duration);
    loaders.set(core.duration._type, std_n.core.duration.load);
    factories.set(core.ti3d._type, core.ti3d);
    factories.set(core.nodeTime._type, core.nodeTime);
    loaders.set(core.nodeTime._type, std_n.core.nodeTime.load);
    factories.set(core.ti10d._type, core.ti10d);
    factories.set(core.function_._type, core.function_);
    factories.set(core.NodeTimeInfo._type, core.NodeTimeInfo);
    factories.set(core.Tuple._type, core.Tuple);
    factories.set(core.nodeIndex._type, core.nodeIndex);
    loaders.set(core.nodeIndex._type, std_n.core.nodeIndex.load);
    factories.set(core.tf3d._type, core.tf3d);
    factories.set(core.GeoPoly._type, core.GeoPoly);
    loaders.set(core.GeoPoly._type, std_n.core.GeoPoly.load);
    factories.set(core.time._type, core.time);
    loaders.set(core.time._type, std_n.core.time.load);
    factories.set(core.DatePart._type, core.DatePart);
    factories.set(core.nodeGeo._type, core.nodeGeo);
    loaders.set(core.nodeGeo._type, std_n.core.nodeGeo.load);
    factories.set(core.ti5d._type, core.ti5d);
    factories.set(core.tf4d._type, core.tf4d);
    factories.set(runtime.Task._type, runtime.Task);
    factories.set(runtime.SecurityEntity._type, runtime.SecurityEntity);
    factories.set(runtime.TaskStatus._type, runtime.TaskStatus);
    factories.set(runtime.Runtime._type, runtime.Runtime);
    factories.set(runtime.RuntimeInfo._type, runtime.RuntimeInfo);
    factories.set(runtime.SecurityFields._type, runtime.SecurityFields);
    factories.set(runtime.UserGroup._type, runtime.UserGroup);
    factories.set(runtime.OpenIDConnect._type, runtime.OpenIDConnect);
    factories.set(runtime.UserRole._type, runtime.UserRole);
    factories.set(runtime.PeriodicTask._type, runtime.PeriodicTask);
    factories.set(runtime.User._type, runtime.User);
    factories.set(runtime.UserGroupPolicy._type, runtime.UserGroupPolicy);
    factories.set(runtime.UserGroupPolicyType._type, runtime.UserGroupPolicyType);
    factories.set(runtime.UserCredential._type, runtime.UserCredential);
    factories.set(runtime.License._type, runtime.License);
    factories.set(runtime.StoreStat._type, runtime.StoreStat);
    factories.set(runtime.System._type, runtime.System);
    factories.set(runtime.SecurityPolicy._type, runtime.SecurityPolicy);
    factories.set(io.FileWriter._type, io.FileWriter);
    loaders.set(io.FileWriter._type, std_n.io.FileWriter.load);
    factories.set(io.JsonFormat._type, io.JsonFormat);
    factories.set(io.JSON._type, io.JSON);
    factories.set(io.TextEncoder._type, io.TextEncoder);
    factories.set(io.CSVColumnBoolean._type, io.CSVColumnBoolean);
    factories.set(io.CSVColumnInteger._type, io.CSVColumnInteger);
    factories.set(io.CSVColumnTime._type, io.CSVColumnTime);
    factories.set(io.CSVColumnFloat._type, io.CSVColumnFloat);
    factories.set(io.CSVColumnIgnored._type, io.CSVColumnIgnored);
    factories.set(io.File._type, io.File);
    loaders.set(io.File._type, std_n.io.File.load);
    factories.set(io.BinaryFormat._type, io.BinaryFormat);
    factories.set(io.Directory._type, io.Directory);
    loaders.set(io.Directory._type, std_n.io.Directory.load);
    factories.set(io.TextFormat._type, io.TextFormat);
    factories.set(io.Env._type, io.Env);
    factories.set(io.CSVColumnString._type, io.CSVColumnString);
    factories.set(io.CSVFormat._type, io.CSVFormat);
    factories.set(io.FileFormat._type, io.FileFormat);
    factories.set(io.AbiWriter._type, io.AbiWriter);
    loaders.set(io.AbiWriter._type, std_n.io.AbiWriter.load);
    factories.set(io.FileEntry._type, io.FileEntry);
    factories.set(io.CSVColumnDate._type, io.CSVColumnDate);
    factories.set(io.AbiReader._type, io.AbiReader);
    loaders.set(io.AbiReader._type, std_n.io.AbiReader.load);
    factories.set(io.FileDescriptor._type, io.FileDescriptor);
    factories.set(io.CSVColumn._type, io.CSVColumn);
    factories.set(debug.ModDesc._type, debug.ModDesc);
    factories.set(debug.TypeAttr._type, debug.TypeAttr);
    factories.set(debug.TypeRef._type, debug.TypeRef);
    factories.set(debug.FnMode._type, debug.FnMode);
    factories.set(debug.FnDesc._type, debug.FnDesc);
    factories.set(debug.TypeDesc._type, debug.TypeDesc);
    factories.set(debug.FnParam._type, debug.FnParam);
    factories.set(debug.ModVarDesc._type, debug.ModVarDesc);
    factories.set(math.MathConstants._type, math.MathConstants);
    factories.set(util.Gaussian._type, util.Gaussian);
    loaders.set(util.Gaussian._type, std_n.util.Gaussian.load);
    factories.set(util.Quantizer._type, util.Quantizer);
    loaders.set(util.Quantizer._type, std_n.util.Quantizer.load);
    factories.set(util.ByteArray._type, util.ByteArray);
    loaders.set(util.ByteArray._type, std_n.util.ByteArray.load);
    factories.set(util.GaussianProfile._type, util.GaussianProfile);
    loaders.set(util.GaussianProfile._type, std_n.util.GaussianProfile.load);
    factories.set(util.BoxPlotF64._type, util.BoxPlotF64);
    factories.set(util.HistogramI64._type, util.HistogramI64);
    loaders.set(util.HistogramI64._type, std_n.util.HistogramI64.load);
    factories.set(util.Random._type, util.Random);
    factories.set(util.NdEncoding._type, util.NdEncoding);
    factories.set(util.HistogramBucket._type, util.HistogramBucket);
    factories.set(util.Iban._type, util.Iban);
    loaders.set(util.Iban._type, std_n.util.Iban.load);
    factories.set(util.HistogramF64._type, util.HistogramF64);
    loaders.set(util.HistogramF64._type, std_n.util.HistogramF64.load);
    factories.set(util.Crypto._type, util.Crypto);
    factories.set(util.TimeWindow._type, util.TimeWindow);
    loaders.set(util.TimeWindow._type, std_n.util.TimeWindow.load);
    factories.set(util.SlidingWindow._type, util.SlidingWindow);
    loaders.set(util.SlidingWindow._type, std_n.util.SlidingWindow.load);
    factories.set(util.Histogram._type, util.Histogram);
    factories.set(util.BoxPlotI64._type, util.BoxPlotI64);
    factories.set(util.BoxPlot._type, util.BoxPlot);
    factories.set(util.Buffer._type, util.Buffer);
    loaders.set(util.Buffer._type, std_n.util.Buffer.load);
    factories.set(util.Assert._type, util.Assert);
    factories.set(util.Queue._type, util.Queue);
    loaders.set(util.Queue._type, std_n.util.Queue.load);
    factories.set(util.ProgressTracker._type, util.ProgressTracker);
    loaders.set(util.ProgressTracker._type, std_n.util.ProgressTracker.load);
  },
  init(abi) {
    this.mapped.length = 107;
    this.mapped[0] = abi.type_by_fqn.get(core.GeoBox._type)!;
    this.mapped[0].resolveGeneratedOffsets('sw','ne');
    this.mapped[1] = abi.type_by_fqn.get(core.nodeList._type)!;
    this.mapped[2] = abi.type_by_fqn.get(core.TimeZone._type)!;
    this.mapped[2].resolveGeneratedOffsetWithValues('Africa_Accra', "AfricaAccra",'Africa_Bamako', "AfricaBamako",'Africa_Banjul', "AfricaBanjul",'Africa_Conakry', "AfricaConakry",'Africa_Dakar', "AfricaDakar",'Africa_Freetown', "AfricaFreetown",'Africa_Lome', "AfricaLome",'Africa_Nouakchott', "AfricaNouakchott",'Africa_Ouagadougou', "AfricaOuagadougou",'Africa_Timbuktu', "AfricaTimbuktu",'Atlantic_Reykjavik', "AtlanticReykjavik",'Atlantic_St_Helena', "AtlanticSt_Helena",'Iceland', "Iceland",'Egypt', "Egypt",'Africa_Maseru', "AfricaMaseru",'Africa_Mbabane', "AfricaMbabane",'Africa_Bangui', "AfricaBangui",'Africa_Brazzaville', "AfricaBrazzaville",'Africa_Douala', "AfricaDouala",'Africa_Kinshasa', "AfricaKinshasa",'Africa_Libreville', "AfricaLibreville",'Africa_Luanda', "AfricaLuanda",'Africa_Malabo', "AfricaMalabo",'Africa_Niamey', "AfricaNiamey",'Africa_Porto_Novo', "AfricaPorto-Novo",'Africa_Blantyre', "AfricaBlantyre",'Africa_Bujumbura', "AfricaBujumbura",'Africa_Gaborone', "AfricaGaborone",'Africa_Harare', "AfricaHarare",'Africa_Kigali', "AfricaKigali",'Africa_Lubumbashi', "AfricaLubumbashi",'Africa_Lusaka', "AfricaLusaka",'Africa_Addis_Ababa', "AfricaAddis_Ababa",'Africa_Asmara', "AfricaAsmara",'Africa_Asmera', "AfricaAsmera",'Africa_Dar_es_Salaam', "AfricaDar_es_Salaam",'Africa_Djibouti', "AfricaDjibouti",'Africa_Kampala', "AfricaKampala",'Africa_Mogadishu', "AfricaMogadishu",'Indian_Antananarivo', "IndianAntananarivo",'Indian_Comoro', "IndianComoro",'Indian_Mayotte', "IndianMayotte",'Libya', "Libya",'America_Atka', "AmericaAtka",'US_Aleutian', "USAleutian",'US_Alaska', "USAlaska",'America_Buenos_Aires', "AmericaBuenos_Aires",'America_Argentina_ComodRivadavia', "AmericaArgentinaComodRivadavia",'America_Catamarca', "AmericaCatamarca",'America_Cordoba', "AmericaCordoba",'America_Rosario', "AmericaRosario",'America_Jujuy', "AmericaJujuy",'America_Mendoza', "AmericaMendoza",'US_Central', "USCentral",'America_Shiprock', "AmericaShiprock",'Navajo', "Navajo",'US_Mountain', "USMountain",'US_Michigan', "USMichigan",'America_Yellowknife', "AmericaYellowknife",'Canada_Mountain', "CanadaMountain",'Canada_Atlantic', "CanadaAtlantic",'Cuba', "Cuba",'America_Fort_Wayne', "AmericaFort_Wayne",'America_Indianapolis', "AmericaIndianapolis",'US_East_Indiana', "USEast-Indiana",'America_Knox_IN', "AmericaKnox_IN",'US_Indiana_Starke', "USIndiana-Starke",'America_Pangnirtung', "AmericaPangnirtung",'Jamaica', "Jamaica",'America_Louisville', "AmericaLouisville",'US_Pacific', "USPacific",'Brazil_West', "BrazilWest",'Mexico_BajaSur', "MexicoBajaSur",'Mexico_General', "MexicoGeneral",'US_Eastern', "USEastern",'Brazil_DeNoronha', "BrazilDeNoronha",'America_Godthab', "AmericaGodthab",'America_Atikokan', "AmericaAtikokan",'America_Cayman', "AmericaCayman",'America_Coral_Harbour', "AmericaCoral_Harbour",'America_Creston', "AmericaCreston",'US_Arizona', "USArizona",'America_Anguilla', "AmericaAnguilla",'America_Antigua', "AmericaAntigua",'America_Aruba', "AmericaAruba",'America_Blanc_Sablon', "AmericaBlanc-Sablon",'America_Curacao', "AmericaCuracao",'America_Dominica', "AmericaDominica",'America_Grenada', "AmericaGrenada",'America_Guadeloupe', "AmericaGuadeloupe",'America_Kralendijk', "AmericaKralendijk",'America_Lower_Princes', "AmericaLower_Princes",'America_Marigot', "AmericaMarigot",'America_Montserrat', "AmericaMontserrat",'America_Port_of_Spain', "AmericaPort_of_Spain",'America_St_Barthelemy', "AmericaSt_Barthelemy",'America_St_Kitts', "AmericaSt_Kitts",'America_St_Lucia', "AmericaSt_Lucia",'America_St_Thomas', "AmericaSt_Thomas",'America_St_Vincent', "AmericaSt_Vincent",'America_Tortola', "AmericaTortola",'America_Virgin', "AmericaVirgin",'Canada_Saskatchewan', "CanadaSaskatchewan",'America_Porto_Acre', "AmericaPorto_Acre",'Brazil_Acre', "BrazilAcre",'Chile_Continental', "ChileContinental",'Brazil_East', "BrazilEast",'Canada_Newfoundland', "CanadaNewfoundland",'America_Ensenada', "AmericaEnsenada",'America_Santa_Isabel', "AmericaSanta_Isabel",'Mexico_BajaNorte', "MexicoBajaNorte",'America_Montreal', "AmericaMontreal",'America_Nassau', "AmericaNassau",'America_Nipigon', "AmericaNipigon",'America_Thunder_Bay', "AmericaThunder_Bay",'Canada_Eastern', "CanadaEastern",'Canada_Pacific', "CanadaPacific",'Canada_Yukon', "CanadaYukon",'America_Rainy_River', "AmericaRainy_River",'Canada_Central', "CanadaCentral",'Asia_Ashkhabad', "AsiaAshkhabad",'Asia_Phnom_Penh', "AsiaPhnom_Penh",'Asia_Vientiane', "AsiaVientiane",'Indian_Christmas', "IndianChristmas",'Asia_Dacca', "AsiaDacca",'Asia_Muscat', "AsiaMuscat",'Indian_Mahe', "IndianMahe",'Indian_Reunion', "IndianReunion",'Asia_Saigon', "AsiaSaigon",'Hongkong', "Hongkong",'Asia_Tel_Aviv', "AsiaTel_Aviv",'Israel', "Israel",'Asia_Katmandu', "AsiaKatmandu",'Asia_Calcutta', "AsiaCalcutta",'Asia_Brunei', "AsiaBrunei",'Asia_Macao', "AsiaMacao",'Asia_Ujung_Pandang', "AsiaUjung_Pandang",'Europe_Nicosia', "EuropeNicosia",'Asia_Bahrain', "AsiaBahrain",'Antarctica_Syowa', "AntarcticaSyowa",'Asia_Aden', "AsiaAden",'Asia_Kuwait', "AsiaKuwait",'ROK', "ROK",'Asia_Chongqing', "AsiaChongqing",'Asia_Chungking', "AsiaChungking",'Asia_Harbin', "AsiaHarbin",'PRC', "PRC",'Asia_Kuala_Lumpur', "AsiaKuala_Lumpur",'Singapore', "Singapore",'ROC', "ROC",'Iran', "Iran",'Asia_Thimbu', "AsiaThimbu",'Japan', "Japan",'Asia_Ulan_Bator', "AsiaUlan_Bator",'Antarctica_Vostok', "AntarcticaVostok",'Asia_Kashgar', "AsiaKashgar",'Asia_Rangoon', "AsiaRangoon",'Indian_Cocos', "IndianCocos",'Atlantic_Faeroe', "AtlanticFaeroe",'Australia_South', "AustraliaSouth",'Australia_Queensland', "AustraliaQueensland",'Australia_Yancowinna', "AustraliaYancowinna",'Australia_North', "AustraliaNorth",'Australia_Currie', "AustraliaCurrie",'Australia_Tasmania', "AustraliaTasmania",'Australia_LHI', "AustraliaLHI",'Australia_Victoria', "AustraliaVictoria",'Australia_West', "AustraliaWest",'Australia_ACT', "AustraliaACT",'Australia_Canberra', "AustraliaCanberra",'Australia_NSW', "AustraliaNSW",'GMT', "GMT",'GMTx0', "GMT+0",'GMT_0', "GMT-0",'GMT0', "GMT0",'Greenwich', "Greenwich",'UCT', "UCT",'UTC', "UTC",'Universal', "Universal",'Zulu', "Zulu",'Europe_Ljubljana', "EuropeLjubljana",'Europe_Podgorica', "EuropePodgorica",'Europe_Sarajevo', "EuropeSarajevo",'Europe_Skopje', "EuropeSkopje",'Europe_Zagreb', "EuropeZagreb",'Arctic_Longyearbyen', "ArcticLongyearbyen",'Atlantic_Jan_Mayen', "AtlanticJan_Mayen",'Europe_Copenhagen', "EuropeCopenhagen",'Europe_Oslo', "EuropeOslo",'Europe_Stockholm', "EuropeStockholm",'Europe_Amsterdam', "EuropeAmsterdam",'Europe_Luxembourg', "EuropeLuxembourg",'Europe_Tiraspol', "EuropeTiraspol",'Eire', "Eire",'Europe_Mariehamn', "EuropeMariehamn",'Asia_Istanbul', "AsiaIstanbul",'Turkey', "Turkey",'Europe_Kiev', "EuropeKiev",'Europe_Uzhgorod', "EuropeUzhgorod",'Europe_Zaporozhye', "EuropeZaporozhye",'Portugal', "Portugal",'Europe_Belfast', "EuropeBelfast",'Europe_Guernsey', "EuropeGuernsey",'Europe_Isle_of_Man', "EuropeIsle_of_Man",'Europe_Jersey', "EuropeJersey",'GB', "GB",'GB_Eire', "GB-Eire",'W_SU', "W-SU",'Europe_Monaco', "EuropeMonaco",'Europe_Bratislava', "EuropeBratislava",'Europe_San_Marino', "EuropeSan_Marino",'Europe_Vatican', "EuropeVatican",'Poland', "Poland",'Europe_Busingen', "EuropeBusingen",'Europe_Vaduz', "EuropeVaduz",'Indian_Kerguelen', "IndianKerguelen",'Antarctica_McMurdo', "AntarcticaMcMurdo",'Antarctica_South_Pole', "AntarcticaSouth_Pole",'NZ', "NZ",'NZ_CHAT', "NZ-CHAT",'Chile_EasterIsland', "ChileEasterIsland",'Pacific_Pohnpei', "PacificPohnpei",'Pacific_Ponape', "PacificPonape",'Pacific_Saipan', "PacificSaipan",'Pacific_Johnston', "PacificJohnston",'US_Hawaii', "USHawaii",'Pacific_Enderbury', "PacificEnderbury",'Kwajalein', "Kwajalein",'Pacific_Midway', "PacificMidway",'Pacific_Samoa', "PacificSamoa",'US_Samoa', "USSamoa",'Antarctica_DumontDUrville', "AntarcticaDumontDUrville",'Pacific_Chuuk', "PacificChuuk",'Pacific_Truk', "PacificTruk",'Pacific_Yap', "PacificYap",'Pacific_Funafuti', "PacificFunafuti",'Pacific_Majuro', "PacificMajuro",'Pacific_Wake', "PacificWake",'Pacific_Wallis', "PacificWallis",'Africa_Abidjan', "AfricaAbidjan",'Africa_Algiers', "AfricaAlgiers",'Africa_Bissau', "AfricaBissau",'Africa_Cairo', "AfricaCairo",'Africa_Casablanca', "AfricaCasablanca",'Africa_Ceuta', "AfricaCeuta",'Africa_El_Aaiun', "AfricaEl_Aaiun",'Africa_Johannesburg', "AfricaJohannesburg",'Africa_Juba', "AfricaJuba",'Africa_Khartoum', "AfricaKhartoum",'Africa_Lagos', "AfricaLagos",'Africa_Maputo', "AfricaMaputo",'Africa_Monrovia', "AfricaMonrovia",'Africa_Nairobi', "AfricaNairobi",'Africa_Ndjamena', "AfricaNdjamena",'Africa_Sao_Tome', "AfricaSao_Tome",'Africa_Tripoli', "AfricaTripoli",'Africa_Tunis', "AfricaTunis",'Africa_Windhoek', "AfricaWindhoek",'America_Adak', "AmericaAdak",'America_Anchorage', "AmericaAnchorage",'America_Araguaina', "AmericaAraguaina",'America_Argentina_Buenos_Aires', "AmericaArgentinaBuenos_Aires",'America_Argentina_Catamarca', "AmericaArgentinaCatamarca",'America_Argentina_Cordoba', "AmericaArgentinaCordoba",'America_Argentina_Jujuy', "AmericaArgentinaJujuy",'America_Argentina_La_Rioja', "AmericaArgentinaLa_Rioja",'America_Argentina_Mendoza', "AmericaArgentinaMendoza",'America_Argentina_Rio_Gallegos', "AmericaArgentinaRio_Gallegos",'America_Argentina_Salta', "AmericaArgentinaSalta",'America_Argentina_San_Juan', "AmericaArgentinaSan_Juan",'America_Argentina_San_Luis', "AmericaArgentinaSan_Luis",'America_Argentina_Tucuman', "AmericaArgentinaTucuman",'America_Argentina_Ushuaia', "AmericaArgentinaUshuaia",'America_Asuncion', "AmericaAsuncion",'America_Bahia', "AmericaBahia",'America_Bahia_Banderas', "AmericaBahia_Banderas",'America_Barbados', "AmericaBarbados",'America_Belem', "AmericaBelem",'America_Belize', "AmericaBelize",'America_Boa_Vista', "AmericaBoa_Vista",'America_Bogota', "AmericaBogota",'America_Boise', "AmericaBoise",'America_Cambridge_Bay', "AmericaCambridge_Bay",'America_Campo_Grande', "AmericaCampo_Grande",'America_Cancun', "AmericaCancun",'America_Caracas', "AmericaCaracas",'America_Cayenne', "AmericaCayenne",'America_Chicago', "AmericaChicago",'America_Chihuahua', "AmericaChihuahua",'America_Ciudad_Juarez', "AmericaCiudad_Juarez",'America_Costa_Rica', "AmericaCosta_Rica",'America_Cuiaba', "AmericaCuiaba",'America_Danmarkshavn', "AmericaDanmarkshavn",'America_Dawson', "AmericaDawson",'America_Dawson_Creek', "AmericaDawson_Creek",'America_Denver', "AmericaDenver",'America_Detroit', "AmericaDetroit",'America_Edmonton', "AmericaEdmonton",'America_Eirunepe', "AmericaEirunepe",'America_El_Salvador', "AmericaEl_Salvador",'America_Fort_Nelson', "AmericaFort_Nelson",'America_Fortaleza', "AmericaFortaleza",'America_Glace_Bay', "AmericaGlace_Bay",'America_Goose_Bay', "AmericaGoose_Bay",'America_Grand_Turk', "AmericaGrand_Turk",'America_Guatemala', "AmericaGuatemala",'America_Guayaquil', "AmericaGuayaquil",'America_Guyana', "AmericaGuyana",'America_Halifax', "AmericaHalifax",'America_Havana', "AmericaHavana",'America_Hermosillo', "AmericaHermosillo",'America_Indiana_Indianapolis', "AmericaIndianaIndianapolis",'America_Indiana_Knox', "AmericaIndianaKnox",'America_Indiana_Marengo', "AmericaIndianaMarengo",'America_Indiana_Petersburg', "AmericaIndianaPetersburg",'America_Indiana_Tell_City', "AmericaIndianaTell_City",'America_Indiana_Vevay', "AmericaIndianaVevay",'America_Indiana_Vincennes', "AmericaIndianaVincennes",'America_Indiana_Winamac', "AmericaIndianaWinamac",'America_Inuvik', "AmericaInuvik",'America_Iqaluit', "AmericaIqaluit",'America_Jamaica', "AmericaJamaica",'America_Juneau', "AmericaJuneau",'America_Kentucky_Louisville', "AmericaKentuckyLouisville",'America_Kentucky_Monticello', "AmericaKentuckyMonticello",'America_La_Paz', "AmericaLa_Paz",'America_Lima', "AmericaLima",'America_Los_Angeles', "AmericaLos_Angeles",'America_Maceio', "AmericaMaceio",'America_Managua', "AmericaManagua",'America_Manaus', "AmericaManaus",'America_Martinique', "AmericaMartinique",'America_Matamoros', "AmericaMatamoros",'America_Mazatlan', "AmericaMazatlan",'America_Menominee', "AmericaMenominee",'America_Merida', "AmericaMerida",'America_Metlakatla', "AmericaMetlakatla",'America_Mexico_City', "AmericaMexico_City",'America_Miquelon', "AmericaMiquelon",'America_Moncton', "AmericaMoncton",'America_Monterrey', "AmericaMonterrey",'America_Montevideo', "AmericaMontevideo",'America_New_York', "AmericaNew_York",'America_Nome', "AmericaNome",'America_Noronha', "AmericaNoronha",'America_North_Dakota_Beulah', "AmericaNorth_DakotaBeulah",'America_North_Dakota_Center', "AmericaNorth_DakotaCenter",'America_North_Dakota_New_Salem', "AmericaNorth_DakotaNew_Salem",'America_Nuuk', "AmericaNuuk",'America_Ojinaga', "AmericaOjinaga",'America_Panama', "AmericaPanama",'America_Paramaribo', "AmericaParamaribo",'America_Phoenix', "AmericaPhoenix",'America_Port_au_Prince', "AmericaPort-au-Prince",'America_Porto_Velho', "AmericaPorto_Velho",'America_Puerto_Rico', "AmericaPuerto_Rico",'America_Punta_Arenas', "AmericaPunta_Arenas",'America_Rankin_Inlet', "AmericaRankin_Inlet",'America_Recife', "AmericaRecife",'America_Regina', "AmericaRegina",'America_Resolute', "AmericaResolute",'America_Rio_Branco', "AmericaRio_Branco",'America_Santarem', "AmericaSantarem",'America_Santiago', "AmericaSantiago",'America_Santo_Domingo', "AmericaSanto_Domingo",'America_Sao_Paulo', "AmericaSao_Paulo",'America_Scoresbysund', "AmericaScoresbysund",'America_Sitka', "AmericaSitka",'America_St_Johns', "AmericaSt_Johns",'America_Swift_Current', "AmericaSwift_Current",'America_Tegucigalpa', "AmericaTegucigalpa",'America_Thule', "AmericaThule",'America_Tijuana', "AmericaTijuana",'America_Toronto', "AmericaToronto",'America_Vancouver', "AmericaVancouver",'America_Whitehorse', "AmericaWhitehorse",'America_Winnipeg', "AmericaWinnipeg",'America_Yakutat', "AmericaYakutat",'Antarctica_Casey', "AntarcticaCasey",'Antarctica_Davis', "AntarcticaDavis",'Antarctica_Macquarie', "AntarcticaMacquarie",'Antarctica_Mawson', "AntarcticaMawson",'Antarctica_Palmer', "AntarcticaPalmer",'Antarctica_Rothera', "AntarcticaRothera",'Antarctica_Troll', "AntarcticaTroll",'Asia_Almaty', "AsiaAlmaty",'Asia_Amman', "AsiaAmman",'Asia_Anadyr', "AsiaAnadyr",'Asia_Aqtau', "AsiaAqtau",'Asia_Aqtobe', "AsiaAqtobe",'Asia_Ashgabat', "AsiaAshgabat",'Asia_Atyrau', "AsiaAtyrau",'Asia_Baghdad', "AsiaBaghdad",'Asia_Baku', "AsiaBaku",'Asia_Bangkok', "AsiaBangkok",'Asia_Barnaul', "AsiaBarnaul",'Asia_Beirut', "AsiaBeirut",'Asia_Bishkek', "AsiaBishkek",'Asia_Chita', "AsiaChita",'Asia_Choibalsan', "AsiaChoibalsan",'Asia_Colombo', "AsiaColombo",'Asia_Damascus', "AsiaDamascus",'Asia_Dhaka', "AsiaDhaka",'Asia_Dili', "AsiaDili",'Asia_Dubai', "AsiaDubai",'Asia_Dushanbe', "AsiaDushanbe",'Asia_Famagusta', "AsiaFamagusta",'Asia_Gaza', "AsiaGaza",'Asia_Hebron', "AsiaHebron",'Asia_Ho_Chi_Minh', "AsiaHo_Chi_Minh",'Asia_Hong_Kong', "AsiaHong_Kong",'Asia_Hovd', "AsiaHovd",'Asia_Irkutsk', "AsiaIrkutsk",'Asia_Jakarta', "AsiaJakarta",'Asia_Jayapura', "AsiaJayapura",'Asia_Jerusalem', "AsiaJerusalem",'Asia_Kabul', "AsiaKabul",'Asia_Kamchatka', "AsiaKamchatka",'Asia_Karachi', "AsiaKarachi",'Asia_Kathmandu', "AsiaKathmandu",'Asia_Khandyga', "AsiaKhandyga",'Asia_Kolkata', "AsiaKolkata",'Asia_Krasnoyarsk', "AsiaKrasnoyarsk",'Asia_Kuching', "AsiaKuching",'Asia_Macau', "AsiaMacau",'Asia_Magadan', "AsiaMagadan",'Asia_Makassar', "AsiaMakassar",'Asia_Manila', "AsiaManila",'Asia_Nicosia', "AsiaNicosia",'Asia_Novokuznetsk', "AsiaNovokuznetsk",'Asia_Novosibirsk', "AsiaNovosibirsk",'Asia_Omsk', "AsiaOmsk",'Asia_Oral', "AsiaOral",'Asia_Pontianak', "AsiaPontianak",'Asia_Pyongyang', "AsiaPyongyang",'Asia_Qatar', "AsiaQatar",'Asia_Qostanay', "AsiaQostanay",'Asia_Qyzylorda', "AsiaQyzylorda",'Asia_Riyadh', "AsiaRiyadh",'Asia_Sakhalin', "AsiaSakhalin",'Asia_Samarkand', "AsiaSamarkand",'Asia_Seoul', "AsiaSeoul",'Asia_Shanghai', "AsiaShanghai",'Asia_Singapore', "AsiaSingapore",'Asia_Srednekolymsk', "AsiaSrednekolymsk",'Asia_Taipei', "AsiaTaipei",'Asia_Tashkent', "AsiaTashkent",'Asia_Tbilisi', "AsiaTbilisi",'Asia_Tehran', "AsiaTehran",'Asia_Thimphu', "AsiaThimphu",'Asia_Tokyo', "AsiaTokyo",'Asia_Tomsk', "AsiaTomsk",'Asia_Ulaanbaatar', "AsiaUlaanbaatar",'Asia_Urumqi', "AsiaUrumqi",'Asia_Ust_Nera', "AsiaUst-Nera",'Asia_Vladivostok', "AsiaVladivostok",'Asia_Yakutsk', "AsiaYakutsk",'Asia_Yangon', "AsiaYangon",'Asia_Yekaterinburg', "AsiaYekaterinburg",'Asia_Yerevan', "AsiaYerevan",'Atlantic_Azores', "AtlanticAzores",'Atlantic_Bermuda', "AtlanticBermuda",'Atlantic_Canary', "AtlanticCanary",'Atlantic_Cape_Verde', "AtlanticCape_Verde",'Atlantic_Faroe', "AtlanticFaroe",'Atlantic_Madeira', "AtlanticMadeira",'Atlantic_South_Georgia', "AtlanticSouth_Georgia",'Atlantic_Stanley', "AtlanticStanley",'Australia_Adelaide', "AustraliaAdelaide",'Australia_Brisbane', "AustraliaBrisbane",'Australia_Broken_Hill', "AustraliaBroken_Hill",'Australia_Darwin', "AustraliaDarwin",'Australia_Eucla', "AustraliaEucla",'Australia_Hobart', "AustraliaHobart",'Australia_Lindeman', "AustraliaLindeman",'Australia_Lord_Howe', "AustraliaLord_Howe",'Australia_Melbourne', "AustraliaMelbourne",'Australia_Perth', "AustraliaPerth",'Australia_Sydney', "AustraliaSydney",'CET', "CET",'CST6CDT', "CST6CDT",'EET', "EET",'EST', "EST",'EST5EDT', "EST5EDT",'Europe_Andorra', "EuropeAndorra",'Europe_Astrakhan', "EuropeAstrakhan",'Europe_Athens', "EuropeAthens",'Europe_Belgrade', "EuropeBelgrade",'Europe_Berlin', "EuropeBerlin",'Europe_Brussels', "EuropeBrussels",'Europe_Bucharest', "EuropeBucharest",'Europe_Budapest', "EuropeBudapest",'Europe_Chisinau', "EuropeChisinau",'Europe_Dublin', "EuropeDublin",'Europe_Gibraltar', "EuropeGibraltar",'Europe_Helsinki', "EuropeHelsinki",'Europe_Istanbul', "EuropeIstanbul",'Europe_Kaliningrad', "EuropeKaliningrad",'Europe_Kirov', "EuropeKirov",'Europe_Kyiv', "EuropeKyiv",'Europe_Lisbon', "EuropeLisbon",'Europe_London', "EuropeLondon",'Europe_Madrid', "EuropeMadrid",'Europe_Malta', "EuropeMalta",'Europe_Minsk', "EuropeMinsk",'Europe_Moscow', "EuropeMoscow",'Europe_Paris', "EuropeParis",'Europe_Prague', "EuropePrague",'Europe_Riga', "EuropeRiga",'Europe_Rome', "EuropeRome",'Europe_Samara', "EuropeSamara",'Europe_Saratov', "EuropeSaratov",'Europe_Simferopol', "EuropeSimferopol",'Europe_Sofia', "EuropeSofia",'Europe_Tallinn', "EuropeTallinn",'Europe_Tirane', "EuropeTirane",'Europe_Ulyanovsk', "EuropeUlyanovsk",'Europe_Vienna', "EuropeVienna",'Europe_Vilnius', "EuropeVilnius",'Europe_Volgograd', "EuropeVolgograd",'Europe_Warsaw', "EuropeWarsaw",'Europe_Zurich', "EuropeZurich",'Factory', "Factory",'HST', "HST",'Indian_Chagos', "IndianChagos",'Indian_Maldives', "IndianMaldives",'Indian_Mauritius', "IndianMauritius",'MET', "MET",'MST', "MST",'MST7MDT', "MST7MDT",'PST8PDT', "PST8PDT",'Pacific_Apia', "PacificApia",'Pacific_Auckland', "PacificAuckland",'Pacific_Bougainville', "PacificBougainville",'Pacific_Chatham', "PacificChatham",'Pacific_Easter', "PacificEaster",'Pacific_Efate', "PacificEfate",'Pacific_Fakaofo', "PacificFakaofo",'Pacific_Fiji', "PacificFiji",'Pacific_Galapagos', "PacificGalapagos",'Pacific_Gambier', "PacificGambier",'Pacific_Guadalcanal', "PacificGuadalcanal",'Pacific_Guam', "PacificGuam",'Pacific_Honolulu', "PacificHonolulu",'Pacific_Kanton', "PacificKanton",'Pacific_Kiritimati', "PacificKiritimati",'Pacific_Kosrae', "PacificKosrae",'Pacific_Kwajalein', "PacificKwajalein",'Pacific_Marquesas', "PacificMarquesas",'Pacific_Nauru', "PacificNauru",'Pacific_Niue', "PacificNiue",'Pacific_Norfolk', "PacificNorfolk",'Pacific_Noumea', "PacificNoumea",'Pacific_Pago_Pago', "PacificPago_Pago",'Pacific_Palau', "PacificPalau",'Pacific_Pitcairn', "PacificPitcairn",'Pacific_Port_Moresby', "PacificPort_Moresby",'Pacific_Rarotonga', "PacificRarotonga",'Pacific_Tahiti', "PacificTahiti",'Pacific_Tarawa', "PacificTarawa",'Pacific_Tongatapu', "PacificTongatapu",'WET', "WET");
    this.mapped[3] = abi.type_by_fqn.get(core.nodeIndexBucket._type)!;
    this.mapped[4] = abi.type_by_fqn.get(core.node._type)!;
    this.mapped[5] = abi.type_by_fqn.get(core.nodeTimeCursor._type)!;
    this.mapped[6] = abi.type_by_fqn.get(core.TableColumnMeta._type)!;
    this.mapped[6].resolveGeneratedOffsets('type','size','index','min','max','avg','std');
    this.mapped[7] = abi.type_by_fqn.get(core.ti2d._type)!;
    this.mapped[8] = abi.type_by_fqn.get(core.Error._type)!;
    this.mapped[9] = abi.type_by_fqn.get(core.tf2d._type)!;
    this.mapped[10] = abi.type_by_fqn.get(core.ErrorCode._type)!;
    this.mapped[10].resolveGeneratedOffsetWithValues('none', 0,'file_not_found', 1,'file_read_error', 2,'file_write_error', 3,'unresolved_function', 4,'too_deep_workspace', 5,'too_deep_iterator', 6,'wrong_path', 7,'parse_error', 8,'out_of_bounds', 9,'division_by_zero', 10,'wrong_operand', 11,'wrong_entrypoint', 12,'wrong_params', 13,'wrong_param_type', 14,'wrong_assert', 15,'wrong_numeric', 16,'wrong_time', 17,'wrong_state', 18,'wrong_null', 19,'unresolved_ref', 20,'assign_error', 21,'read_field_requires_obj', 22,'read_offset_requires_array', 23,'write_offset_requires_array', 24,'write_field_requires_object', 25,'min_higher_max_error', 26,'negative_std', 27,'interrupted', 28,'throw', 29,'wrong_type', 30,'wrong_dimension', 31,'unsupported_operation', 32,'unsupported_type', 33,'too_large', 34,'dimensions_mismatch', 35,'not_initialized', 36,'timeout', 37,'unauthorized', 38,'forbidden', 39,'runtime_error', 40,'compile_error', 41,'update_error', 42);
    this.mapped[11] = abi.type_by_fqn.get(core.ti4d._type)!;
    this.mapped[12] = abi.type_by_fqn.get(core.SamplingMode._type)!;
    this.mapped[12].resolveGeneratedOffsetWithValues('fixed', 0,'fixed_reg', 1,'adaptative', 2,'dense', 3);
    this.mapped[13] = abi.type_by_fqn.get(core.DurationUnit._type)!;
    this.mapped[13].resolveGeneratedOffsetWithValues('microseconds', 1,'milliseconds', 1000,'seconds', 1000000,'minutes', 60000000,'hours', 3600000000,'days', 86400000000,'weeks', 604800000000,'months', 2628000000000,'years', 31536000000000);
    this.mapped[14] = abi.type_by_fqn.get(core.TensorType._type)!;
    this.mapped[14].resolveGeneratedOffsetWithValues('i32', 4,'i64', 8,'f32', 4,'f64', 8,'c64', 8,'c128', 16);
    this.mapped[15] = abi.type_by_fqn.get(core.Table._type)!;
    this.mapped[16] = abi.type_by_fqn.get(core.geo._type)!;
    this.mapped[16].static_values = [abi.createGeo(-85.05112876,-179.999999958),abi.createGeo(85.05112876,179.999999958)];
    this.mapped[17] = abi.type_by_fqn.get(core.ti6d._type)!;
    this.mapped[18] = abi.type_by_fqn.get(core.Tensor._type)!;
    this.mapped[19] = abi.type_by_fqn.get(core.GeoCircle._type)!;
    this.mapped[19].resolveGeneratedOffsets('center','radius');
    this.mapped[20] = abi.type_by_fqn.get(core.Date._type)!;
    this.mapped[21] = abi.type_by_fqn.get(core.duration._type)!;
    this.mapped[22] = abi.type_by_fqn.get(core.ti3d._type)!;
    this.mapped[23] = abi.type_by_fqn.get(core.nodeTime._type)!;
    this.mapped[24] = abi.type_by_fqn.get(core.ti10d._type)!;
    this.mapped[25] = abi.type_by_fqn.get(core.function_._type)!;
    this.mapped[26] = abi.type_by_fqn.get(core.NodeTimeInfo._type)!;
    this.mapped[26].resolveGeneratedOffsets('size','from','to');
    this.mapped[27] = abi.type_by_fqn.get(core.Tuple._type)!;
    this.mapped[27].resolveGeneratedOffsets('x','y');
    this.mapped[28] = abi.type_by_fqn.get(core.nodeIndex._type)!;
    this.mapped[29] = abi.type_by_fqn.get(core.tf3d._type)!;
    this.mapped[30] = abi.type_by_fqn.get(core.GeoPoly._type)!;
    this.mapped[31] = abi.type_by_fqn.get(core.time._type)!;
    this.mapped[31].static_values = [abi.createTime(-9223372036854775808n),abi.createTime(9223372036854775807n)];
    this.mapped[32] = abi.type_by_fqn.get(core.DatePart._type)!;
    this.mapped[32].resolveGeneratedOffsetWithValues('years', 0,'months', 1,'days', 2,'hours', 3,'minutes', 4,'seconds', 5,'microseconds', 6);
    this.mapped[33] = abi.type_by_fqn.get(core.nodeGeo._type)!;
    this.mapped[34] = abi.type_by_fqn.get(core.ti5d._type)!;
    this.mapped[35] = abi.type_by_fqn.get(core.tf4d._type)!;
    this.mapped[36] = abi.type_by_fqn.get(runtime.Task._type)!;
    this.mapped[36].resolveGeneratedOffsets('id','user','parent','mod','type','fun','progress','remaining','creation','start','duration','status','sub_waiting','sub_tasks_all');
    this.mapped[37] = abi.type_by_fqn.get(runtime.SecurityEntity._type)!;
    this.mapped[37].resolveGeneratedOffsets('id','name','activated');
    this.mapped[38] = abi.type_by_fqn.get(runtime.TaskStatus._type)!;
    this.mapped[38].resolveGeneratedOffsetWithValues('empty', 0,'waiting', 1,'running', 2,'cancelled', 3,'error', 4,'ended', 5);
    this.mapped[39] = abi.type_by_fqn.get(runtime.Runtime._type)!;
    this.mapped[40] = abi.type_by_fqn.get(runtime.RuntimeInfo._type)!;
    this.mapped[40].resolveGeneratedOffsets('version','arch','timezone','license','io_threads','bg_threads','fg_threads','mem_total','mem_worker','nb_ctx','store_stats');
    this.mapped[41] = abi.type_by_fqn.get(runtime.SecurityFields._type)!;
    this.mapped[41].resolveGeneratedOffsets('email','name','first_name','last_name','roles','groups');
    this.mapped[42] = abi.type_by_fqn.get(runtime.UserGroup._type)!;
    this.mapped[42].resolveGeneratedOffsets('id','name','activated');
    this.mapped[43] = abi.type_by_fqn.get(runtime.OpenIDConnect._type)!;
    this.mapped[43].resolveGeneratedOffsets('url','clientId');
    this.mapped[44] = abi.type_by_fqn.get(runtime.UserRole._type)!;
    this.mapped[44].resolveGeneratedOffsets('name','permissions');
    this.mapped[45] = abi.type_by_fqn.get(runtime.PeriodicTask._type)!;
    this.mapped[45].resolveGeneratedOffsets('name','user_id','args','start','every');
    this.mapped[46] = abi.type_by_fqn.get(runtime.User._type)!;
    this.mapped[46].resolveGeneratedOffsets('id','name','activated','full_name','email','role','permissions_flags','groups','groups_flags','external');
    this.mapped[47] = abi.type_by_fqn.get(runtime.UserGroupPolicy._type)!;
    this.mapped[47].resolveGeneratedOffsets('group_id','type');
    this.mapped[48] = abi.type_by_fqn.get(runtime.UserGroupPolicyType._type)!;
    this.mapped[48].resolveGeneratedOffsetWithValues('read', 0,'write', 1,'execute', 2);
    this.mapped[49] = abi.type_by_fqn.get(runtime.UserCredential._type)!;
    this.mapped[49].resolveGeneratedOffsets('offset','pass');
    this.mapped[50] = abi.type_by_fqn.get(runtime.License._type)!;
    this.mapped[50].resolveGeneratedOffsets('name','start','end','company','max_workers','max_memory','max_store','extra_1','extra_2','extra_3','extra_4');
    this.mapped[51] = abi.type_by_fqn.get(runtime.StoreStat._type)!;
    this.mapped[51].resolveGeneratedOffsets('capacity_bytes','allocated_bytes','allocated_ratio','remained_bytes','remained_ratio','used_bytes','used_ratio','available_bytes','available_ratio');
    this.mapped[52] = abi.type_by_fqn.get(runtime.System._type)!;
    this.mapped[53] = abi.type_by_fqn.get(runtime.SecurityPolicy._type)!;
    this.mapped[53].resolveGeneratedOffsets('entities','credentials','roles','fields');
    this.mapped[54] = abi.type_by_fqn.get(io.FileWriter._type)!;
    this.mapped[55] = abi.type_by_fqn.get(io.JsonFormat._type)!;
    this.mapped[56] = abi.type_by_fqn.get(io.JSON._type)!;
    this.mapped[57] = abi.type_by_fqn.get(io.TextEncoder._type)!;
    this.mapped[57].resolveGeneratedOffsetWithValues('plain', null,'base64', null,'base64url', null,'hexadecimal', null);
    this.mapped[58] = abi.type_by_fqn.get(io.CSVColumnBoolean._type)!;
    this.mapped[58].resolveGeneratedOffsets('name','mandatory');
    this.mapped[59] = abi.type_by_fqn.get(io.CSVColumnInteger._type)!;
    this.mapped[59].resolveGeneratedOffsets('name','mandatory');
    this.mapped[60] = abi.type_by_fqn.get(io.CSVColumnTime._type)!;
    this.mapped[60].resolveGeneratedOffsets('name','mandatory','unit');
    this.mapped[61] = abi.type_by_fqn.get(io.CSVColumnFloat._type)!;
    this.mapped[61].resolveGeneratedOffsets('name','mandatory');
    this.mapped[62] = abi.type_by_fqn.get(io.CSVColumnIgnored._type)!;
    this.mapped[62].resolveGeneratedOffsets('name','mandatory');
    this.mapped[63] = abi.type_by_fqn.get(io.File._type)!;
    this.mapped[64] = abi.type_by_fqn.get(io.BinaryFormat._type)!;
    this.mapped[65] = abi.type_by_fqn.get(io.Directory._type)!;
    this.mapped[66] = abi.type_by_fqn.get(io.TextFormat._type)!;
    this.mapped[67] = abi.type_by_fqn.get(io.Env._type)!;
    this.mapped[68] = abi.type_by_fqn.get(io.CSVColumnString._type)!;
    this.mapped[68].resolveGeneratedOffsets('name','mandatory','trim','try_number','try_json','values','encoder');
    this.mapped[69] = abi.type_by_fqn.get(io.CSVFormat._type)!;
    this.mapped[69].resolveGeneratedOffsets('header_lines','infer','separator','string_delimiter','decimal_separator','thousands_separator','columns');
    this.mapped[70] = abi.type_by_fqn.get(io.FileFormat._type)!;
    this.mapped[71] = abi.type_by_fqn.get(io.AbiWriter._type)!;
    this.mapped[72] = abi.type_by_fqn.get(io.FileEntry._type)!;
    this.mapped[73] = abi.type_by_fqn.get(io.CSVColumnDate._type)!;
    this.mapped[73].resolveGeneratedOffsets('name','mandatory','format','tz','as_time');
    this.mapped[74] = abi.type_by_fqn.get(io.AbiReader._type)!;
    this.mapped[75] = abi.type_by_fqn.get(io.FileDescriptor._type)!;
    this.mapped[75].resolveGeneratedOffsets('uri','size','last_modification');
    this.mapped[76] = abi.type_by_fqn.get(io.CSVColumn._type)!;
    this.mapped[76].resolveGeneratedOffsets('name','mandatory');
    this.mapped[77] = abi.type_by_fqn.get(debug.ModDesc._type)!;
    this.mapped[77].resolveGeneratedOffsets('name','lib','functions','types','vars');
    this.mapped[78] = abi.type_by_fqn.get(debug.TypeAttr._type)!;
    this.mapped[78].resolveGeneratedOffsets('name','type','is_static');
    this.mapped[79] = abi.type_by_fqn.get(debug.TypeRef._type)!;
    this.mapped[79].resolveGeneratedOffsets('name','module','generics','nullable');
    this.mapped[80] = abi.type_by_fqn.get(debug.FnMode._type)!;
    this.mapped[80].resolveGeneratedOffsetWithValues('read_only', null,'copy_on_write', null,'volatile', null,'write', null);
    this.mapped[81] = abi.type_by_fqn.get(debug.FnDesc._type)!;
    this.mapped[81].resolveGeneratedOffsets('module','name','parent_type','params','return_type','is_static','is_task','is_exclusive','is_reserved','is_exposed','mode','permissions');
    this.mapped[82] = abi.type_by_fqn.get(debug.TypeDesc._type)!;
    this.mapped[82].resolveGeneratedOffsets('module','name','methods','attrs','is_abstract','is_enum');
    this.mapped[83] = abi.type_by_fqn.get(debug.FnParam._type)!;
    this.mapped[83].resolveGeneratedOffsets('name','type');
    this.mapped[84] = abi.type_by_fqn.get(debug.ModVarDesc._type)!;
    this.mapped[84].resolveGeneratedOffsets('module','name','type');
    this.mapped[85] = abi.type_by_fqn.get(math.MathConstants._type)!;
    this.mapped[85].static_values = [2.718281828,1.442695041,0.434294482,0.693147181,2.302585093,3.141592654,1.570796327,0.785398163,0.318309886,0.636619772,1.128379167,1.414213562,0.707106781];
    this.mapped[86] = abi.type_by_fqn.get(util.Gaussian._type)!;
    this.mapped[87] = abi.type_by_fqn.get(util.Quantizer._type)!;
    this.mapped[88] = abi.type_by_fqn.get(util.ByteArray._type)!;
    this.mapped[89] = abi.type_by_fqn.get(util.GaussianProfile._type)!;
    this.mapped[90] = abi.type_by_fqn.get(util.BoxPlotF64._type)!;
    this.mapped[90].resolveGeneratedOffsets('min','max','whiskerLow','whiskerHigh','percentile1','percentile5','percentile25','percentile50','percentile75','percentile95','percentile99','countOutliersLow','countOutliersHigh','percentageOutliersLow','percentageOutliersHigh','sum','avg','std','size');
    this.mapped[91] = abi.type_by_fqn.get(util.HistogramI64._type)!;
    this.mapped[92] = abi.type_by_fqn.get(util.Random._type)!;
    this.mapped[92].resolveGeneratedOffsets('seed','v');
    this.mapped[93] = abi.type_by_fqn.get(util.NdEncoding._type)!;
    this.mapped[94] = abi.type_by_fqn.get(util.HistogramBucket._type)!;
    this.mapped[94].resolveGeneratedOffsetWithValues('from', 0,'to', 1,'count', 2,'percentage', 3);
    this.mapped[95] = abi.type_by_fqn.get(util.Iban._type)!;
    this.mapped[96] = abi.type_by_fqn.get(util.HistogramF64._type)!;
    this.mapped[97] = abi.type_by_fqn.get(util.Crypto._type)!;
    this.mapped[98] = abi.type_by_fqn.get(util.TimeWindow._type)!;
    this.mapped[99] = abi.type_by_fqn.get(util.SlidingWindow._type)!;
    this.mapped[100] = abi.type_by_fqn.get(util.Histogram._type)!;
    this.mapped[101] = abi.type_by_fqn.get(util.BoxPlotI64._type)!;
    this.mapped[101].resolveGeneratedOffsets('min','max','whiskerLow','whiskerHigh','percentile1','percentile5','percentile25','percentile50','percentile75','percentile95','percentile99','countOutliersLow','countOutliersHigh','percentageOutliersLow','percentageOutliersHigh','sum','avg','std','size');
    this.mapped[102] = abi.type_by_fqn.get(util.BoxPlot._type)!;
    this.mapped[102].resolveGeneratedOffsets('min','max','whiskerLow','whiskerHigh','percentile1','percentile5','percentile25','percentile50','percentile75','percentile95','percentile99','countOutliersLow','countOutliersHigh','percentageOutliersLow','percentageOutliersHigh','sum','avg','std','size');
    this.mapped[103] = abi.type_by_fqn.get(util.Buffer._type)!;
    this.mapped[104] = abi.type_by_fqn.get(util.Assert._type)!;
    this.mapped[105] = abi.type_by_fqn.get(util.Queue._type)!;
    this.mapped[106] = abi.type_by_fqn.get(util.ProgressTracker._type)!;
  },
};
